spring:
    application:
      name: content-service
    cloud:
      nacos:
        config:
          server-addr: 192.168.1.146:8848
          namespace: dev02
          group: xcplus
    config:
      import:
        - optional:nacos:feign.yaml?group=xcplus&refreshEnabled=true   #项目feign配置
        - nacos:content-service.yaml
#
logging:
  level:
    root: INFO
    com:
      example:
        xcpluscontentservice:
          content:
            mapper: DEBUG
