spring:
  application:
    name: xcgateway
  cloud:
    nacos:
      config:
        server-addr: 192.168.1.146:8848
        namespace: dev02
        group: xcplus
      discovery:
        server-addr: 192.168.1.146:8848
        namespace: dev02
        group: xcplus
  config:
    import:
      - nacos:gateway.yaml

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: DEBUG
