spring:
  application:
    name: content-api
  cloud:
    nacos:
      config:
        server-addr: 192.168.1.146:8848
        namespace: dev02
        group: xcplus
      discovery:
        server-addr: 192.168.1.146:8848
        namespace: dev02
        group: xcplus
  config:
     import:
       - optional:nacos:xcplus-common.yaml?group=xcplus-common&refreshEnabled=false   #项目公用配置
       - nacos:content-api.yaml   #子项目特殊配置
