spring:
  application:
    name: system-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.146:11337/xc_system?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: app
    password: app123456



