server:
  servlet:
    context-path: /content
  port: 63040
spring:
    application:
      name: content-api
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.1.146:11337/xc_content?serverTimezone=UTC&userUnicode=true&useSSL=false&
      username: app
      password: app123456
    main:
      allow-circular-references: true

swagger:
  title: "学成内容管理"
  description: "学成内容管理描述信息"
  enable: true
  base-package: com.example.xcpluscontentapi
  version: 1.0.0